"""Graph state definitions and data structures for the Deep Research agent."""

import operator
from typing import Annotated, Any, Dict, List, Optional

from langchain_core.messages import MessageLikeRepresentation
from langgraph.graph import MessagesState
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


###################
# Structured Outputs
###################
class ConductEndpointsTracing(BaseModel):
    """Call this tool to retrieve endpoints threats(generated by Falco) from the database."""
    research_topic: str = Field(
        description="The topic to hunt terminal threat by retrieving Falco relevant information from database.",
    )

class ConductApplicationTracing(BaseModel):
    """Call this tool to retrieve application threats(generated by OpenRasp) from the database."""
    research_topic: str = Field(
        description="The topic to hunt application threats by retrieving OpenRasp relevant information from database.",
    )

class ConductNetworkTracing(BaseModel):
    """Call this tool to retrieve network threats(generated by Suricata) from the database. This tool also supports retrieving information from internet webs."""
    research_topic: str = Field(
        description="The topic to hunt network threats(generated by Suricata) information from database.",
    )

class ResearchComplete(BaseModel):
    """Call this tool to indicate that the research is complete."""

class Summary(BaseModel):
    """Research summary with key findings."""
    
    summary: str
    key_excerpts: str

class ClarifyWithUser(BaseModel):
    """Model for user clarification requests."""
    
    need_clarification: bool = Field(
        description="Whether the user needs to be asked a clarifying question.",
    )
    question: str = Field(
        description="A question to ask the user to clarify the report scope",
    )
    verification: str = Field(
        description="Verify message that we will start research after the user has provided the necessary information.",
    )

class ResearchQuestion(BaseModel):
    """Research question and brief for guiding research."""
    
    research_brief: str = Field(
        description="A research question that will be used to guide the research.",
    )

class Technique(BaseModel):
    """技术层级 - MITRE ATT&CK Technique"""
    tech_id: str = Field(..., description="技术ID，如T1059")
    tech_name: str = Field(..., description="技术名称")
    description: str = Field(..., description="技术描述")
    procedures: List[str] = Field(..., description="关联的过程描述列表，包含攻击者IP、行为特征、攻击目标等证据信息")
    event_ids: List[str] = Field(default_factory=list, description="与该技术有关的事件ID列表，从而可以追溯到具体的事件数据")


class TTP(BaseModel):
    """战术技术程序 - MITRE ATT&CK Tactic"""
    id: str = Field(..., description="战术ID，如TA0001")
    name: str = Field(..., description="战术名称")
    description: str = Field(..., description="战术描述")
    techniques: List[Technique] = Field(..., description="包含的技术列表")
    event_ids: List[str] = Field(..., description="与该战术有关的事件ID列表")


class AnalysisReport(BaseModel):
    """威胁狩猎分析报告模型 - 只包含TTP列表"""
    ttps: List[TTP] = Field(
        description="发现的TTP列表（战术-技术-过程），按照MITRE ATT&CK框架结构组织",
    )
    final_report: str = Field(
        description="最终的威胁狩猎分析报告正文，使用Markdown格式，适合向利益相关方展示",
    )


###################
# State Definitions
###################

def override_reducer(current_value, new_value):
    """Reducer function that allows overriding values in state."""
    if isinstance(new_value, dict) and new_value.get("type") == "override":
        return new_value.get("value", new_value)
    else:
        return operator.add(current_value, new_value)

def simple_override_reducer(current_value, new_value):
    """Simple reducer that always overrides the current value."""
    return new_value
    
class AgentInputState(MessagesState):
    """InputState is only 'messages'."""

class AgentState(MessagesState):
    """Main agent state containing messages and research data."""
    
    supervisor_messages: Annotated[list[MessageLikeRepresentation], override_reducer]
    research_brief: Optional[str]
    raw_notes: Annotated[list[str], override_reducer] = []
    notes: Annotated[list[str], override_reducer] = []
    research_thoughts: Annotated[list[str], override_reducer] = []  # supervisor think_tool 的思考记录
    final_report: str
    ttps: Optional[str] = None
    feedback_round: int = 0  # 人机反馈轮次计数，防止无限循环
    mitre_enrichment: Optional[Dict[str, Any]] = None

class SupervisorState(TypedDict):
    """State for the supervisor that manages research tasks."""

    supervisor_messages: Annotated[list[MessageLikeRepresentation], override_reducer]
    research_brief: str
    notes: Annotated[list[str], override_reducer] = []
    research_iterations: int = 0
    raw_notes: Annotated[list[str], override_reducer] = []
    research_thoughts: Annotated[list[str], override_reducer] = []  # supervisor think_tool 的思考记录

class ResearcherState(TypedDict):
    """State for individual researchers conducting research."""
    
    researcher_messages: Annotated[list[MessageLikeRepresentation], operator.add]
    tool_call_iterations: int = 0
    research_topic: str
    compressed_research: str
    raw_notes: Annotated[list[str], override_reducer] = []
    mappings: Annotated[list[dict], simple_override_reducer] = []

class ResearcherOutputState(BaseModel):
    """Output state from individual researchers."""
    
    compressed_research: str
    raw_notes: Annotated[list[str], override_reducer] = []